<div id="wrap">
    <div id="menu">
        <h4>PAGES</h4>
        
        <div id="pagesList">
        <?php foreach($pagesList as $page_id=>$page_title):?>
            <a href='#' id='<?php echo $page_id?>' class='view_page'><?php echo $page_title?></a><br>
        <?php endforeach; ?>
        </div>
        <a href='#' id='addPage'>(add page)</a><br>
    </div>

    <div id="content">
    
    </div>
</div>
